parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string
- name: stageForSigningFolder
  type: string
- name: stageForUnsignedFolder
  type: string

stages:
- stage: 'Official_Build_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Build and Publish Package for ${{ parameters.moduleFolderName }}'
  pool:
    vmImage: windows-2019
  jobs:
  # Build
  #########################################################################################
  - job: 'Build'
    displayName: 'Build Official AVS-Automation-AdminTools for ${{ parameters.moduleFolderName }}'
    steps:
    - task: PowerShell@2
      displayName: 'Set Build Version for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/setBuildVersion.ps1'
        arguments: '$(Build.BuildNumber)'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Versioning Module for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/updateModuleVersion.ps1'
        arguments: '$(System.DefaultWorkingDirectory)\${{ parameters.moduleFolderName }}\${{ parameters.moduleFolderName }}.psd1'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}' #PSGallery publishing guidelines: https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/publishing-packages/publishing-a-package?view=powershell-7.1#pre-validate-your-item
      inputs:
        filePath: 'tests/prevalidateModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}'
        pwsh: true
    - publish: $(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}
      artifact: ${{ parameters.stageForSigningFolder }}
      displayName: Stage Files for Signing
    - publish: $(System.DefaultWorkingDirectory)
      artifact: ${{ parameters.stageForUnsignedFolder }}
      displayName: Stage Unsigned Module
