parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string

stages:
- stage: 'Unofficial_Build_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Build and Publish Package for ${{ parameters.moduleFolderName }}'
  pool:
    vmImage: windows-2019
  jobs:
  - job: Build_and_Publish_Job
    displayName: 'Build Unofficial AVS-Automation-AdminTools for ${{ parameters.moduleFolderName }}'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: Scripting Metadata
        scriptLocation: 'inlineScript'
        scriptType: 'pscore'
        inlineScript: |
          $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
          Write-Host "##vso[task.setsecret]$accessToken"
          $env:AZURE_DEVOPS_EXT_PAT=$accessToken
          az artifacts universal download `
            --organization $(feedAuthority) `
            --project=$(feedProject) `
            --scope project `
            --feed $(metadataFeed) `
            --name shuttle `
            --version $(shuttleVersion) `
            --path shuttle          
        displayName: Prepare shuttle
    - task: PowerShell@2
      displayName: 'Set Build Version for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/setBuildVersion.ps1'
        arguments: '$(Build.BuildNumber)'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Versioning Module for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/updateModuleVersion.ps1'
        arguments: '$(System.DefaultWorkingDirectory)\${{ parameters.moduleFolderName }}\${{ parameters.moduleFolderName }}.psd1 -IsPR'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}' #PSGallery publishing guidelines: https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/publishing-packages/publishing-a-package?view=powershell-7.1#pre-validate-your-item
      inputs:
        filePath: 'tests/prevalidateModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}'
        pwsh: true
    - powershell: |
        echo "+ ${{ parameters.moduleFolderName }}@$(moduleVersion)" > shuttle/baseline
        dotnet shuttle/Shuttle.dll generate
      env:
        METADATA: uri://console
      displayName: 'Generate metadata'
