parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string

stages:
- stage: 'Build_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Build ${{ parameters.moduleFolderName }}'
  dependsOn: [Compliance_Checks]
  pool:
    vmImage: ubuntu-20.04
  variables:
    previewFeed: "https://pkgs.dev.azure.com/avs-oss/Public/_packaging/Unofficial-AVS-Automation-AdminTools/nuget/v2"
  jobs:
  - job: 'Build'
    displayName: 'Preview build for ${{ parameters.moduleFolderName }}'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: Scripting Metadata
        scriptLocation: 'inlineScript'
        scriptType: 'pscore'
        inlineScript: |
          $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
          Write-Host "##vso[task.setsecret]$accessToken"
          Write-Host "##vso[task.setvariable variable=adoAccessToken;issecret=true]$accessToken"
          $env:AZURE_DEVOPS_EXT_PAT=$accessToken
          az artifacts universal download `
            --organization $(feedAuthority) `
            --project=$(feedProject) `
            --scope project `
            --feed $(metadataFeed) `
            --name shuttle `
            --version $(shuttleVersion) `
            --path shuttle          
        displayName: Prepare shuttle

    - task: PowerShell@2
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
        pwsh: true
    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: 'tests/prevalidateModules.ps1'
        arguments: '${{ parameters.moduleFolderName }}'
        pwsh: true
    - task: NuGetAuthenticate@1
    - pwsh: 
        .build-tools/publish.ps1 
          '$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1' 
          $(Build.BuildNumber) 
          "${{ variables.previewFeed }}"
          dev 
      displayName: Publish Developer Version
    - pwsh: 
        .build-tools/publish.ps1 
          '$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1' 
          $(Build.BuildNumber) 
          "${{ variables.previewFeed }}"
          preview 
      displayName: Publish Preview Version
    - pwsh: |
        echo "+ ${{ parameters.moduleFolderName }}@$(moduleVersion)" > shuttle/baseline
        dotnet shuttle/Shuttle.dll generate
      env:
        AZURE_DEVOPS_EXT_PAT: $(adoAccessToken)
        METADATA: $(feedAuthority)/$(feedProject)/_artifacts/feed/$(metadataFeed)
      displayName: 'Generate metadata'
