parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string
- name: genMetadata
  type: boolean
  default: true

stages:
- stage: 'Validation_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Validate Package ${{ parameters.moduleFolderName }}'
  dependsOn: []
  jobs:
  - job: Validate
    displayName: 'Validate ${{ parameters.moduleFolderName }}'
    variables:
      destination: '$(System.DefaultWorkingDirectory)/tmp'
    steps:
    - task: NuGetAuthenticate@1

    - pwsh: |
        dotnet tool update -g powershell `
          --version $(PS_VERSION)
        dotnet tool install AVS.ScriptingMetadata.Shuttle `
          --tool-path shuttle `
          --version $(shuttleVersion)
      displayName: Prepare tools

    - pwsh: |
        .build-tools/registerSources.ps1 $(consumptionFeedUrl) $(destination)
        .build-tools/getRequiredModules.ps1 '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'

    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: 'tests/prevalidateModules.ps1'
        arguments: >
          "${{ parameters.moduleFolderName }}"
        pwsh: true

    - task: PowerShell@2
      inputs:
        filePath: .build-tools/publish.ps1 
        arguments: >
          '$(System.AccessToken)'
          "$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1"
          "$(Build.BuildNumber)"
          "$(destination)"
      displayName: 'Test publish'

    - pwsh: |
        $env:PSModulePath = "$(System.DefaultWorkingDirectory):$env:PSModulePath"
        echo "+ ${{ parameters.moduleFolderName }}@$(moduleVersion)" > shuttle/baseline
        shuttle/shuttle generate
      env:
        METADATA: uri://console
        DATAPATH: $(System.DefaultWorkingDirectory)/shuttle
      displayName: 'Generate metadata'
      condition: eq(${{ parameters.genMetadata }}, true)
