parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string
- name: genMetadata
  type: boolean
  default: true

stages:
- stage: 'Validation_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Validate Package ${{ parameters.moduleFolderName }}'
  dependsOn: []
  jobs:
  - job: Validate
    displayName: 'Validate ${{ parameters.moduleFolderName }}'
    variables:
      destination: '$(System.DefaultWorkingDirectory)/tmp'
    steps:
    - task: NuGetAuthenticate@1

    - pwsh: |
        az artifacts universal download `
            --organization $(consumptionAuthority) `
            --project=$(consumptionProject) `
            --scope project `
            --feed $(consumptionFeed) `
            --name shuttle `
            --version $(shuttleVersion) `
            --path shuttle          
        .build-tools/registerSources.ps1 $(consumptionFeedUrl) $(destination)
        .build-tools/getRequiredModules.ps1 '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: 'tests/prevalidateModules.ps1'
        arguments: >
          "${{ parameters.moduleFolderName }}"
        pwsh: true

    - task: PowerShell@2
      inputs:
        filePath: .build-tools/publish.ps1 
        arguments: >
          "$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1"
          "$(Build.BuildNumber)"
          "$(destination)"
      displayName: 'Test publish'

    - pwsh: |
        echo "+ ${{ parameters.moduleFolderName }}@$(moduleVersion)" > shuttle/baseline
        dotnet shuttle/Shuttle.dll generate
      env:
        METADATA: uri://console
      displayName: 'Generate metadata'
      condition: eq(${{ parameters.genMetadata }}, true)
