parameters:
- name: moduleFolderName
  type: string
- name: moduleDisplayName
  type: string
- name: genMetadata
  type: boolean
  default: true

stages:
- stage: 'Build_${{ parameters.moduleDisplayName }}' # Valid stage name cannot contain the character '.'
  displayName: 'Build ${{ parameters.moduleFolderName }}'
  dependsOn: [Compliance_Checks]
  pool:
    os: linux
    image: avs-management-ubuntu-22.04-1es-image
    name: avs-management-1es-hosted-pool
  jobs:
  - job: 'Build'
    displayName: 'Preview build for ${{ parameters.moduleFolderName }}'
    steps:
    - task: NuGetAuthenticate@1
    - task: AzureCLI@2
      inputs:
        azureSubscription: Scripting Metadata
        scriptLocation: 'inlineScript'
        scriptType: 'pscore'
        inlineScript: |
          $accessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
          Write-Host "##vso[task.setsecret]$accessToken"
          Write-Host "##vso[task.setvariable variable=accessToken;issecret=true]$accessToken"
      displayName: Login to Azure

    - pwsh: |
        dotnet tool update -g powershell `
        --version $(PS_VERSION) `
          --add-source $(consumptionFeedUrl)
        dotnet tool install AVS.ScriptingMetadata.Shuttle `
          --tool-path shuttle `
          --version $(shuttleVersion) `
          --add-source $(consumptionFeedUrl)
      displayName: Prepare tools

    - pwsh: |
        .build-tools/registerSources.ps1 $(consumptionFeedUrl) $(previewFeedUrl)
        .build-tools/getRequiredModules.ps1 '${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
      displayName: 'Restore Dependencies for ${{ parameters.moduleFolderName }}'

    - task: PowerShell@2
      displayName: 'Pre-Validate Module and Scripts for ${{ parameters.moduleFolderName }}'
      inputs:
        filePath: tests/prevalidateModules.ps1
        arguments: >
          "${{ parameters.moduleFolderName }}"
        pwsh: true

    - task: PowerShell@2
      inputs:
        filePath: .build-tools/publish.ps1 
        arguments: >
          "$(accessToken)"
          "$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1"
          "$(Build.BuildNumber)"
          "$(previewFeedUrl)"
          dev 
      displayName: Publish Developer Version

    - task: PowerShell@2
      inputs:
        filePath: .build-tools/publish.ps1 
        arguments: >
          "$(accessToken)"
          '$(System.DefaultWorkingDirectory)/${{ parameters.moduleFolderName }}/${{ parameters.moduleFolderName }}.psd1'
          "$(Build.BuildNumber)"
          "$(previewFeedUrl)"
          preview
      displayName: Publish Preview Version

    - pwsh: |
        $env:PSModulePath = "$(System.DefaultWorkingDirectory):$env:PSModulePath"
        echo "+ ${{ parameters.moduleFolderName }}@$(moduleVersion)-dev" > shuttle/baseline
        shuttle/shuttle generate
      env:
        METADATA: $(metadataAuthority)/$(metadataProject)/_artifacts/feed/$(metadataFeed)
        DATAPATH: $(System.DefaultWorkingDirectory)/shuttle
      displayName: 'Generate metadata'
      condition: eq(${{ parameters.genMetadata }}, true)
