#
# Module manifest for module 'Microsoft.AVS.CDR'
#
# Generated by: Microsoft
#
# Generated on: 1/5/2026
#

@{
    RootModule = 'Microsoft.AVS.CDR.psm1'

    ModuleVersion = '1.0.1'

    # CompatiblePSEditions = @()

    GUID = '44aa8397-56c2-428e-a0db-eb6c7f167c2b'

    Author = 'Microsoft'

    CompanyName = 'Microsoft'

    Copyright = '(c) Microsoft. All rights reserved.'

    Description = 'Conservative dependency resolver'

    PowerShellVersion = '7.4'

    RequiredModules = @()

    FunctionsToExport = @('Install-PSResourcePinned', 'Import-ModulePinned')

    CmdletsToExport = '*'

    VariablesToExport = '*'

    AliasesToExport = '*'

    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('PowerCLI', 'AVS')

            LicenseUri = 'https://raw.githubusercontent.com/Azure/Microsoft.AVS.Management/refs/heads/main/LICENSE'

            ProjectUri = 'https://github.com/Azure/Microsoft.AVS.Management'

            # IconUri = ''

            # ReleaseNotes = ''

            # Prerelease = ''

            # RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfoURI = ''

    # DefaultCommandPrefix = ''

}

