# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
- stage: Build 
  displayName: Build
  pool:
    vmImage: windows-2019
  jobs:
  - job: Build_Job
    displayName: Build AVS-Automation-AdminTools

    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'build/copyModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: 'build/build.ps1'
        pwsh: true