# Starter pipeline

trigger:
- mibart/trialBranch

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: Compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: ComplianceJob
    pool:
      vmImage: Windows-latest
    steps:
    - checkout: self
    - checkout: ComplianceRepo
    - template: ci-compliance.yml@ComplianceRepo

# extends:
#   template: v2/OneBranch.Official.CrossPlat.yml@templates
#   parameters:
#     stages:
#     - stage: build
#       jobs:
#       - job: main
#         pool:
#           type: windows
#         variables:
#           ob_outputDirectory: '$(Build.SourcesDirectory)\out'
#         ##steps: []
#         steps:
#         - script: echo "Actual task to perform, TBD"
#           displayName: 'Run simple echo command'

#         - task: onebranch.pipeline.signing@1
#           displayName: '🔒 Setup Signing'
#           inputs:
#             command: 'setup'
#             signing_environment: 'azure-ado'
#             use_cache_v2: true
#             install_cert: true
#             watch_directory: $(Build.SourcesDirectory)
#             cache_directory: $(Build.SourcesDirectory)\\.sign\\.cache
            
#         - task: onebranch.pipeline.signing@1
#           inputs:
#             command: 'sign'
#             signing_environment: 'azure-ado'
#             signing_profile: 'external_distribution'
#             cp_code: 'CP-230012'
#             files_to_sign: '**/*.exe;**/*.dll;**/*.ps1;**/*.psd1**/*.psm1;!**/PowerCLI-Example-Scripts-master/**'
#             search_root: '$(Build.SourcesDirectory)'