# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
- stage: Build 
  displayName: Build
  pool:
    vmImage: vs2019-win2016
  jobs:
  - job: Build_Job
    displayName: Build AVS-Automation-AdminTools

    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/azure-avs-automation-admintools/build/copyModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/azure-avs-automation-admintools/build/build.ps1'
        pwsh: true