parameters:
- name: publishManagementPackage
  type: boolean
  default: true
- name: publishVmfsPackage
  type: boolean
  default: true
- name: publishVvolsPackage
  type: boolean
  default: true
- name: publishNfsPackage
  type: boolean
  default: true

trigger:
- main

pr:
- none

variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    globalSdl:
      tsa:
        enabled: true
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
        enabled: true
      policheck:
        break: false
      armory:
        break: false
        suppressionsFile: $(Build.SourcesDirectory)/.config/ArmorySuppressions.json
      cg:
        failOnAlert: false
      sbom:
        validate: false

stages:
- template: templates/obp-common-compliance-stages.yml@self

- ${{ if eq(parameters.publishManagementPackage, true) }}:
  - template: templates/obp-common-preview-build-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.managementModuleFolderName }}
      moduleDisplayName: ${{ variables.managementModuleDisplayName }}

- ${{ if eq(parameters.publishVmfsPackage, true) }}:
  - template: templates/obp-common-preview-build-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.vmfsModuleFolderName }}
      moduleDisplayName: ${{ variables.vmfsModuleDisplayName }}

- ${{ if eq(parameters.publishVvolsPackage, true) }}:
  - template: templates/obp-common-preview-build-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.vvolsModuleFolderName }}
      moduleDisplayName: ${{ variables.vvolsModuleDisplayName }}

- ${{ if eq(parameters.publishNfsPackage, true) }}:
  - template: templates/obp-common-preview-build-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.nfsModuleFolderName }}
      moduleDisplayName: ${{ variables.nfsModuleDisplayName }}