parameters:
- name: publishManagementPackage
  type: boolean
  default: false
- name: publishVmfsPackage
  type: boolean
  default: false

trigger:
- main

pr:
- none
########################################
variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version
#######################################

stages:
- template: templates/common-officialBuild-stages.yml@self
  parameters:
    publishPackage: ${{ parameters.publishManagementPackage }}
    moduleFolderName: ${{ variables.managementModuleFolderName }}
    moduleDisplayName: ${{ variables.managementModuleDisplayName }}
    stageForSigningFolder: ${{ variables.stageForSigningFolder }}
    stageForUnsignedFolder: ${{ variables.stageForUnsignedFolder }}

- template: templates/common-officialBuild-stages.yml@self
  parameters:
    publishPackage: ${{ parameters.publishVmfsPackage }}
    moduleFolderName: ${{ variables.vmfsModuleFolderName }}
    moduleDisplayName: ${{ variables.vmfsModuleDisplayName }}
    stageForSigningFolder: ${{ variables.stageForSigningFolder }}
    stageForUnsignedFolder: ${{ variables.stageForUnsignedFolder }}
