trigger:
  batch: true
  branches:
    include:
    - main

variables:
  MAJOR: 0
  minor: 1

name: $(MAJOR).$(minor).$(Rev:r)

stages:
- stage: Official_Build 
  displayName: Build and Publish Package
  pool:
    vmImage: windows-2019
  jobs:
  - job: Build_and_Publish_Job
    displayName: Build Unofficial AVS-Automation-AdminTools
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/updateModuleVersion.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: 'build/build.ps1'
        pwsh: true
    - task: NuGetAuthenticate@0
    - task: PowerShell@2
      inputs:
        filePath: 'package/publishPackage.ps1'
        arguments: -buildType 'official'
        pwsh: true