trigger:
- main

pr:
- none
########################################
variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version
#######################################

stages:
- template: templates/common-officialBuild-stages.yml@self
  parameters:
    moduleFolderName: ${{ variables.managementModuleFolderName }}
    stageForSigningFolder: ${{ variables.stageForSigningFolder }}
    stageForUnsignedFolder: ${{ variables.stageForUnsignedFolder }}

- template: templates/common-officialBuild-stages.yml@self
  parameters:
    moduleFolderName: ${{ variables.vmfsModuleFolderName }}
    stageForSigningFolder: ${{ variables.stageForSigningFolder }}
    stageForUnsignedFolder: ${{ variables.stageForUnsignedFolder }}
