trigger:
- main

pr:
- none
########################################
variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version
#######################################

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    settings:
      skipBuildTagsForGitHubPullRequests: true
    featureFlags:
      autoBaseline: false
    sdl:
      psscriptanalyzer:
        enabled: true
        break: false
      policy: M365
      sourceAnalysisPool:
        os: windows
        image: avs-management-windows-2022-1es-image
        name: avs-management-1es-hosted-pool
    stages:
    - template: templates/common-compliance-stages.yml@self

    - template: templates/common-preview-build-stages.yml@self
      parameters:
        moduleFolderName: ${{ variables.managementModuleFolderName }}
        moduleDisplayName: ${{ variables.managementModuleDisplayName }}

    - template: templates/common-preview-build-stages.yml@self
      parameters:
        moduleFolderName: ${{ variables.vmfsModuleFolderName }}
        moduleDisplayName: ${{ variables.vmfsModuleDisplayName }}

    - template: templates/common-preview-build-stages.yml@self
      parameters:
        moduleFolderName: ${{ variables.vvolsModuleFolderName }}
        moduleDisplayName: ${{ variables.vvolsModuleDisplayName }}

    - template: templates/common-preview-build-stages.yml@self
      parameters:
        moduleFolderName: ${{ variables.nfsModuleFolderName }}
        moduleDisplayName: ${{ variables.nfsModuleDisplayName }}

    - template: templates/common-preview-build-stages.yml@self
      parameters:
        moduleFolderName: ${{ variables.cdrModuleFolderName }}
        moduleDisplayName: ${{ variables.cdrModuleDisplayName }}
        genMetadata: false
