# https://aka.ms/yaml

pr:
  branches:
    include:
    - main
  drafts: false

stages:
- stage: Build 
  displayName: Build
  pool:
    vmImage: windows-2019
  jobs:
  - job: Build_and_Publish_Job
    displayName: Build AVS-Automation-AdminTools
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'build/copyModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: 'build/build.ps1'
        pwsh: true
    - task: NuGetAuthenticate@0
    - task: PowerShell@2
      inputs:
        filePath: 'package/publishUnofficialPackage.ps1'
        pwsh: true