# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main
  drafts: false
  autoCancel: false

variables:
  MAJOR: 0
  minor: 1

name: $(MAJOR).$(minor).$(Rev:r)

stages:
- stage: Build_and_Publish 
  displayName: Build and Publish Package
  pool:
    vmImage: windows-2019
  jobs:
  - job: Build_and_Publish_Job
    displayName: Build Unofficial AVS-Automation-AdminTools
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/updateModuleVersion.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: 'build/build.ps1'
        pwsh: true
    - task: NuGetAuthenticate@0
    - task: PowerShell@2
      inputs:
        filePath: 'package/publishPackage.ps1'
        pwsh: true
- stage: Compliance
  displayName: Compliance
  dependsOn: Official_Build
  jobs:
  - job: Check_Compliance
    steps:
    - pwsh: |
        Write-Output "---- NO COMPLIANCE TASKS----"
- stage: Test
  displayName: Test
  dependsOn: Official_Build
  jobs:
  - job: Run_Tests
    steps:
    - pwsh: |
        Write-Output "---- NO TEST RUNNING----"
- stage: Release
  displayName: Release
  dependsOn: 
  - Official_Build
  - Compliance
  - Test
  jobs:
  - job: Release
    steps:
    - pwsh: |
        Write-Output "---- NO RELEAST TASKS----"