# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main
  drafts: false
  autoCancel: false
######################################

variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version
######################################

stages:
- template: templates/common-unofficialBuild-stages.yml@self
  parameters:
    moduleFolderName: ${{ variables.managementModuleFolderName }}

- template: templates/common-unofficialBuild-stages.yml@self
  parameters:
    moduleFolderName: ${{ variables.vmfsModuleFolderName }}
