# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main
  drafts: false
  autoCancel: false

variables:
  MAJOR: 0
  minor: 1

name: $(MAJOR).$(minor).$(Rev:r)

stages:
- stage: Build 
  displayName: Build
  pool:
    vmImage: windows-2019
  jobs:
  - job: Get_Required_Modules
    displayName: Get Required Modules
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/getRequiredModules.ps1'
        pwsh: true
  - job: Update_PS_Module_Version
    dependsOn: Get_Required_Modules
    displayName: Update Module Version
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '.build-tools/updateModuleVersion.ps1'
        pwsh: true
  - job: Build_and_Publish_Job
    dependsOn: Update_PS_Module_Version
    displayName: Build Unofficial AVS-Automation-AdminTools
    steps:
    - task: PowerShell@2
      inputs:
        filePath: 'build/copyModules.ps1'
        pwsh: true
    - task: PowerShell@2
      inputs:
        filePath: 'build/build.ps1'
        pwsh: true
    - task: NuGetAuthenticate@0
    - task: PowerShell@2
      inputs:
        filePath: 'package/publishUnofficialPackage.ps1'
        pwsh: true