# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main
  drafts: false
  autoCancel: false
######################################

variables:
- template: vars.yml

name: $(Rev:r) # Provide build run number (i.e., Build.BuildNumber) that is used as patch for build version and ultimately module version
######################################

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      image: ubuntu-latest
      name: Azure-Pipelines-1ESPT-ExDShared
  sdl:
    sourceAnalysisPool:
      os: windows
      image: windows-latest
      name: Azure-Pipelines-1ESPT-ExDShared
  stages:
  - template: templates/common-validation-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.managementModuleFolderName }}
      moduleDisplayName: ${{ variables.managementModuleDisplayName }}

  - template: templates/common-validation-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.vmfsModuleFolderName }}
      moduleDisplayName: ${{ variables.vmfsModuleDisplayName }}

  - template: templates/common-validation-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.vvolsModuleFolderName }}
      moduleDisplayName: ${{ variables.vvolsModuleDisplayName }}

  - template: templates/common-validation-stages.yml@self
    parameters:
      moduleFolderName: ${{ variables.nfsModuleFolderName }}
      moduleDisplayName: ${{ variables.nfsModuleDisplayName }}
